FROM alpine:3.21

VOLUME /build

ENV BUILD_TYPE=Debug
ENV TARGET=stm32f103rb

WORKDIR /usr/local/vcu

# Install system dependencies
RUN apk update
RUN apk add cmake ninja

# Install ARM toolchain

COPY . .

# Run build script and move target binaries
CMD [ "scripts/build_docker.sh" ]
