FROM alpine:3.21

VOLUME /build

ENV BUILD_TYPE=Release
ENV TARGET=stm32f103rb

WORKDIR /usr/local/vcu

# Install system dependencies
RUN apk update
RUN apk add binutils-arm-none-eabi gcc-arm-none-eabi newlib-arm-none-eabi cmake

COPY . .

# Run build script and move target binaries
CMD [ "scripts/build_docker.sh" ]
